project:
  type: book

book:
  title: "CASA0023 Learning Diary"
  author: "Yidian Liu"
  date: "1/28/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - chapter2.qmd
    - chapter3.qmd
    - chapter4.qmd
    - week6.qmd
    - week7.qmd
    - week8.qmd
    - week9.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual
output-dir: _book

resources:
  - slides/
